---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - python
  eslint:
    enabled: true
  fixme:
    enabled: true
  radon:
    enabled: true
    config:
      treshold: "c"
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths: 
  - /quero_cultura/static/*
