doc-warnings: true
test-warnings: true
strictness: high
max-line-length: 120
uses:
  - django
autodetect: true
requirements:
  - requirements.txt
python-targets:
  - 3
pep8:
  full: true
pylint:
  options:
    docstring-min-length: 10
mccabe:
  run: true
