version: '3'

services:
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./quero_cultura/templates/quero_cultura:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  redis:
    image: redis
    ports:
      - "6379:6379"
  web:
    build: .
    command: chmod +x boot.sh
    command: service varnish start
    command: ./boot.sh
    volumes:
      - .:/code
      - ./varnish:/etc/varnish/
    ports:
      - "8000:8000"
      - "6081:6081"
      - "6082:6082"
      - "80:80"
    depends_on:
      - mongo
      - redis
