version: '3'

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  mongo:
    image: mongo
    ports:
      - "27017:27017"
      
  redis:
    image: redis
    ports:
      - "6379:6379"

  web:
    build: .
    command: chmod +x boot.sh
    command: ./boot.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - nginx
      - mongo
      - redis

  postgres:
    image: postgres
    environment:
        POSTGRES_PASSWORD: 12345
        POSTGRES_DB: metabase
        POSTGRES_USER: quero_cultura
        POSTGRES_PASSWORD: 123456
    ports:
        - "5433:5432"
    volumes:
        - ./postgres_metabase:/postgres_metabase

  metabase:
    image: metabase/metabase
    ports:
      - "3000:3000"
    environment:
        MB_DB_TYPE: postgres
        MB_DB_DBNAME: metabase
        MB_DB_PORT: 5432
        MB_DB_USER: quero_cultura
        MB_DB_PASS: 123456
        MB_DB_HOST: postgres
    depends_on:
      - postgres
      - dkr

  dkr:
    image: docker
    privileged: true
    working_dir: "/dkr"
    volumes:
      - ".:/dkr"
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: docker exec 20172querocultura_postgres_1 bash -c "sleep 5 && psql metabase quero_cultura -f /postgres_metabase/metabase.sql"

    depends_on:
      - postgres
